"""Type and layout tool specs."""

from __future__ import annotations

from .catalog_schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="type.list",
        backend_method="type_list",
        description="List data types with filtering and pagination support.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "query": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.get",
        backend_method="type_get",
        description="Return details for a data type by name or full path.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "name": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.define_c",
        backend_method="type_define_c",
        description="Define a new data type from a C declaration.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "declaration": {"type": "string"},
                "name": {"type": "string"},
                "category": {"type": "string"},
            },
            "required": ["session_id", "declaration"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.rename",
        backend_method="type_rename",
        description="Rename an existing data type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "name": {"type": "string"},
                "new_name": {"type": "string"},
            },
            "required": ["session_id", "new_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.delete",
        backend_method="type_delete",
        description="Delete a data type by name or full path.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "name": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.parse_c",
        backend_method="type_parse_c",
        description=(
            "Parse a C declaration and return the resulting type without necessarily"
            "committing it."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "declaration": {"type": "string"},
                "name": {"type": "string"},
                "category": {"type": "string"},
            },
            "required": ["session_id", "declaration"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.apply_at",
        backend_method="type_apply_at",
        description="Apply a data type at an address in the listing.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_type": {"type": "string"},
                "length": {"type": "integer"},
                "clear_existing": {"type": "boolean"},
            },
            "required": ["session_id", "address", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.create",
        backend_method="struct_create",
        description="Create a structure data type in a chosen category.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "category": {"type": "string"},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.field.add",
        backend_method="struct_field_add",
        description="Add a field to a structure at a specific offset or append position.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "field_name": {"type": "string"},
                "data_type": {"type": "string"},
                "offset": {"type": "integer"},
                "length": {"type": "integer"},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.field.rename",
        backend_method="struct_field_rename",
        description="Rename a structure field.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "old_name": {"type": "string"},
                "new_name": {"type": "string"},
                "offset": {"type": "integer"},
                "ordinal": {"type": "integer"},
            },
            "required": ["session_id", "new_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.enum.create",
        backend_method="enum_create",
        description="Create an enum data type in a chosen category.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "category": {"type": "string"},
                "size": {"type": "integer"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.enum.member.add",
        backend_method="enum_member_add",
        description="Add a named value to an enum data type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "enum_path": {"type": "string"},
                "enum_name": {"type": "string"},
                "name": {"type": "string"},
                "value": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "name", "value"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.category.list",
        backend_method="type_category_list",
        description="List data type categories under a path, optionally recursively.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "recursive": {"type": "boolean"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.category.create",
        backend_method="type_category_create",
        description="Create a new data type category path.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "path": {"type": "string"}},
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.archives.list",
        backend_method="type_archives_list",
        description="List the current program archive plus attached source archives.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.source_archives.list",
        backend_method="type_source_archives_list",
        description="List source archives referenced by the current data type manager.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="type.get_by_id",
        backend_method="type_get_by_id",
        description="Look up a data type by internal ID, universal ID, or source archive ID.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "data_type_id": {"type": "integer"},
                "universal_id": {"type": "integer"},
                "source_archive_id": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.get",
        backend_method="layout_struct_get",
        description="Return a structure definition together with its components.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.resize",
        backend_method="layout_struct_resize",
        description="Resize a structure to a specific total length.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "length"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.field.replace",
        backend_method="layout_struct_field_replace",
        description=(
            "Replace an existing structure field with a new type, size, name, orcomment."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "offset": {"type": "integer"},
                "data_type": {"type": "string"},
                "length": {"type": "integer"},
                "field_name": {"type": "string"},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "offset", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.field.clear",
        backend_method="layout_struct_field_clear",
        description="Clear a field from a structure by offset, ordinal, or field name.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "offset": {"type": "integer"},
            },
            "required": ["session_id", "offset"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.field.comment.set",
        backend_method="layout_struct_field_comment_set",
        description="Set or clear the comment on a structure field.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "offset": {"type": "integer"},
                "ordinal": {"type": "integer"},
                "field_name": {"type": "string"},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "comment"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.bitfield.add",
        backend_method="layout_struct_bitfield_add",
        description="Insert a bitfield into a structure at a byte and bit offset.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "struct_path": {"type": "string"},
                "struct_name": {"type": "string"},
                "byte_offset": {"type": "integer"},
                "byte_width": {"type": "integer"},
                "bit_offset": {"type": "integer"},
                "data_type": {"type": "string"},
                "bit_size": {"type": "integer"},
                "field_name": {"type": "string"},
                "comment": {"type": "string"},
            },
            "required": [
                "session_id",
                "byte_offset",
                "byte_width",
                "bit_offset",
                "data_type",
                "bit_size",
            ],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.union.create",
        backend_method="layout_union_create",
        description="Create a union data type in a chosen category.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "category": {"type": "string"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.union.member.add",
        backend_method="layout_union_member_add",
        description="Add a member to a union data type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "union_path": {"type": "string"},
                "union_name": {"type": "string"},
                "field_name": {"type": "string"},
                "data_type": {"type": "string"},
                "length": {"type": "integer"},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.union.member.remove",
        backend_method="layout_union_member_remove",
        description="Remove a member from a union data type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "union_path": {"type": "string"},
                "union_name": {"type": "string"},
                "ordinal": {"type": "integer"},
                "field_name": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.enum.member.remove",
        backend_method="layout_enum_member_remove",
        description="Remove a named member from an enum data type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "enum_path": {"type": "string"},
                "enum_name": {"type": "string"},
                "name": {"type": "string"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.inspect.components",
        backend_method="layout_inspect_components",
        description="Inspect the component layout of a composite data type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "name": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="layout.struct.fill_from_decompiler",
        backend_method="layout_struct_fill_from_decompiler",
        description=(
            "Build or extend a structure from decompiler-observed usage of avariable."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "ordinal": {"type": "integer"},
                "storage": {"type": "string"},
                "create_new_structure": {"type": "boolean"},
                "create_class_if_needed": {"type": "boolean"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
)
