"""Function, parameter, variable, and stack-frame tool specs."""

from __future__ import annotations

from .catalog_schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="function.list",
        backend_method="binary_functions",
        description="List functions in the program with filtering and pagination support.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "query": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.at",
        backend_method="binary_get_function_at",
        description="Return the function that starts at, or contains, a specific address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.callers",
        backend_method="function_callers",
        description="List the functions that call a specific function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.callees",
        backend_method="function_callees",
        description="List the functions called by a specific function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.signature.get",
        backend_method="function_signature_get",
        description="Return the full signature of a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.signature.set",
        backend_method="function_signature_set",
        description="Apply a full C-style signature declaration to a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "signature": {"type": "string"},
            },
            "required": ["session_id", "function_start", "signature"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.variables",
        backend_method="function_variables",
        description="List parameters and local variables for a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.rename",
        backend_method="function_rename",
        description="Rename an existing function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.by_name",
        backend_method="function_by_name",
        description="Look up a function by name and return its details.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "exact": {"type": "boolean"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="variable.rename",
        backend_method="function_variable_rename",
        description="Rename a local variable or parameter.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "new_name": {"type": "string"},
                "ordinal": {"type": "integer"},
                "storage": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name", "new_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="variable.retype",
        backend_method="function_variable_retype",
        description="Change the data type of a local variable or parameter.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "data_type": {"type": "string"},
                "ordinal": {"type": "integer"},
                "storage": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.return_type.set",
        backend_method="function_return_type_set",
        description="Set the return type of a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_type": {"type": "string"},
            },
            "required": ["session_id", "function_start", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.create",
        backend_method="function_create",
        description="Create a new function at a given address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.delete",
        backend_method="function_delete",
        description="Delete a function at a given address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.report",
        backend_method="report_function_summary",
        description=(
            "Return a richer function report with signature, variables, call graph"
            "edges, xrefs, and decompilation output."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.batch.run",
        backend_method="batch_run_on_functions",
        description="Run one supported action across a filtered batch of functions.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "action": {"type": "string"},
                "query": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "action"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.body.set",
        backend_method="function_body_set",
        description="Replace the body range of an existing function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.calling_conventions.list",
        backend_method="function_calling_conventions_list",
        description="List calling conventions available in the current program.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.calling_convention.set",
        backend_method="function_calling_convention_set",
        description="Set the calling convention used by a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.flags.set",
        backend_method="function_flags_set",
        description=("Update function flags such as varargs, inline, noreturn, or customstorage."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "varargs": {"type": "boolean"},
                "inline": {"type": "boolean"},
                "noreturn": {"type": "boolean"},
                "custom_storage": {"type": "boolean"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="function.thunk.set",
        backend_method="function_thunk_set",
        description="Mark a function as a thunk to another function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "thunk_target": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start", "thunk_target"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="parameter.add",
        backend_method="parameter_add",
        description="Add a new parameter to a function with a chosen type and storage.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "data_type": {"type": "string"},
                "ordinal": {"type": "integer"},
                "stack_offset": {"type": "integer"},
                "register": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="parameter.remove",
        backend_method="parameter_remove",
        description="Remove a parameter from a function by ordinal or name.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "ordinal": {"type": "integer"},
                "name": {"type": "string"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="parameter.move",
        backend_method="parameter_move",
        description="Reorder a parameter to a new ordinal within the signature.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "ordinal": {"type": "integer"},
                "new_ordinal": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "ordinal", "new_ordinal"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="parameter.replace",
        backend_method="parameter_replace",
        description="Replace an existing parameter definition by ordinal or name.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "ordinal": {"type": "integer"},
                "name": {"type": "string"},
                "new_name": {"type": "string"},
                "data_type": {"type": "string"},
                "stack_offset": {"type": "integer"},
                "register": {"type": "string"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="variable.local.create",
        backend_method="variable_local_create",
        description=("Create a local variable with explicit type, storage, and optionalcomment."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "data_type": {"type": "string"},
                "first_use_offset": {"type": "integer"},
                "stack_offset": {"type": "integer"},
                "register": {"type": "string"},
                "storage_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="variable.local.remove",
        backend_method="variable_local_remove",
        description="Remove a local variable from a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "storage": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="variable.comment.set",
        backend_method="variable_comment_set",
        description="Set or clear the comment attached to a local variable or parameter.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "comment": {"type": "string"},
                "ordinal": {"type": "integer"},
                "storage": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name", "comment"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="stackframe.variable.create",
        backend_method="stackframe_variable_create",
        description="Create a stack-frame variable at a specific stack offset.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "stack_offset": {"type": "integer"},
                "data_type": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name", "stack_offset", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="stackframe.variable.clear",
        backend_method="stackframe_variable_clear",
        description="Clear a stack-frame variable at a specific stack offset.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "stack_offset": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "stack_offset"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="stackframe.variables",
        backend_method="stackframe_variables",
        description="List stack-frame variables for a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
)
