"""Symbol, comment, bookmark, namespace, class, and tag tool specs."""

from __future__ import annotations

from .catalog_schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="symbol.list",
        backend_method="binary_symbols",
        description="List symbols with filtering and pagination support.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "include_dynamic": {"type": "boolean"},
                "query": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="comment.get",
        backend_method="annotation_comment_get",
        description="Return one comment type from a specific address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "comment_type": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "scope": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="comment.set",
        backend_method="annotation_comment_set",
        description="Set or clear a comment of a selected type at an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "comment": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "comment_type": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "scope": {"type": "string"},
            },
            "required": ["session_id", "comment"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="symbol.rename",
        backend_method="annotation_symbol_rename",
        description="Rename an existing symbol.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "new_name": {"type": "string"},
                "old_name": {"type": "string"},
            },
            "required": ["session_id", "address", "new_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="symbol.create",
        backend_method="annotation_symbol_create",
        description="Create a new symbol or label at an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "make_primary": {"type": "boolean"},
            },
            "required": ["session_id", "address", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="symbol.delete",
        backend_method="annotation_symbol_delete",
        description="Delete a symbol at an address, optionally by name.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="symbol.by_name",
        backend_method="symbol_by_name",
        description="Look up a symbol by name and return its details.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "exact": {"type": "boolean"},
                "limit": {"type": "integer"},
                "include_dynamic": {"type": "boolean"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="bookmark.add",
        backend_method="bookmark_add",
        description="Add a bookmark at an address with a type, category, and comment.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "category": {"type": "string"},
                "comment": {"type": "string"},
                "bookmark_type": {"type": "string"},
            },
            "required": ["session_id", "address", "category", "comment"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="bookmark.list",
        backend_method="bookmark_list",
        description="List bookmarks, optionally scoped to an address or bookmark type.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "bookmark_type": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="tag.add",
        backend_method="tag_add",
        description="Create or reuse a function tag and attach it to a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="tag.list",
        backend_method="tag_list",
        description="List tags for one function or across the whole program.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="symbol.primary.set",
        backend_method="symbol_primary_set",
        description="Mark a selected symbol as the primary symbol at its address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="namespace.create",
        backend_method="namespace_create",
        description="Create a namespace under an optional parent namespace.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "parent": {"type": "string"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="class.create",
        backend_method="class_create",
        description="Create a class namespace for recovered methods or fields.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "parent": {"type": "string"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="symbol.namespace.move",
        backend_method="symbol_namespace_move",
        description="Move a symbol into a different namespace.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "namespace": {"type": "string"},
                "name": {"type": "string"},
            },
            "required": ["session_id", "address", "namespace"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="comment.get_all",
        backend_method="comment_get_all",
        description=(
            "Return all available comment types at an address, with optional functioncomments."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "include_function": {"type": "boolean"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="comment.list",
        backend_method="comment_list",
        description="List comments matching range, type, text, and pagination filters.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "comment_type": {"type": "string"},
                "query": {"type": "string"},
                "case_sensitive": {"type": "boolean"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="bookmark.remove",
        backend_method="bookmark_remove",
        description="Remove bookmarks at an address, optionally filtered by type or category.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "bookmark_type": {"type": "string"},
                "category": {"type": "string"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="bookmark.clear",
        backend_method="bookmark_clear",
        description=(
            "Remove bookmarks in an address range, optionally filtered by bookmarktype."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
                "bookmark_type": {"type": "string"},
            },
            "required": ["session_id", "start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="tag.remove",
        backend_method="tag_remove",
        description="Remove a function tag from a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="tag.stats",
        backend_method="tag_stats",
        description="Summarize function tags and the number of functions using each one.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
)
