"""Search tool specs."""

from __future__ import annotations

from .catalog_schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="search.defined_strings",
        backend_method="binary_strings",
        description="List defined strings discovered in the program.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "query": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="search.resolve",
        backend_method="address_resolve",
        description="Resolve a symbol name or expression into an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "query": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "query"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="search.text",
        backend_method="search_text",
        description="Search for text across defined strings and raw memory matches.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "text": {"type": "string"},
                "case_sensitive": {"type": "boolean"},
                "defined_strings_only": {"type": "boolean"},
                "encoding": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "text"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="search.bytes",
        backend_method="search_bytes",
        description="Search program memory for an exact byte pattern.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "pattern_base64": {"type": "string"},
                "pattern_hex": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="search.constants",
        backend_method="search_constants",
        description="Search instructions for scalar constant operands that match a value.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "value": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "value"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="search.instructions",
        backend_method="search_instructions",
        description="Search instructions by mnemonic or rendered instruction text.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "query": {"type": "string"},
                "case_sensitive": {"type": "boolean"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "query"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="search.pcode",
        backend_method="search_pcode",
        description="Search p-code operations by mnemonic or rendered op text.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "query": {"type": "string"},
                "case_sensitive": {"type": "boolean"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "query"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
)
