"""Analysis, decompiler, p-code, graph, and task tool specs."""

from __future__ import annotations

from .schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="analysis.status",
        backend_method="analysis_status",
        description="Return the current auto-analysis status for the session.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.update",
        backend_method="analysis_update",
        description="Start auto-analysis in the background and return immediately.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.update_and_wait",
        backend_method="analysis_update_and_wait",
        description="Run auto-analysis and wait until it completes.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.options.list",
        backend_method="analysis_options_list",
        description="List available analysis options together with their current values.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "query": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.options.get",
        backend_method="analysis_options_get",
        description="Return the current value of a specific analysis option.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "name": {"type": "string"}},
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.options.set",
        backend_method="analysis_options_set",
        description="Update the value of an analysis option for the current session.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "value": {},
            },
            "required": ["session_id", "name", "value"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.function",
        backend_method="decomp_function",
        description=(
            "Decompile a function as complete raw Ghidra C by default, or as a non-compilable "
            "compact view with generated local declarations elided."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "timeout_secs": {"type": "integer"},
                "view": {"type": "string", "enum": ["raw", "compact"]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="pcode.function",
        backend_method="pcode_function",
        description="Return per-instruction p-code for a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="pcode.op.at",
        backend_method="pcode_op_at",
        description="Return the p-code ops generated by the instruction at an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="graph.basic_blocks",
        backend_method="function_basic_blocks",
        description="List the basic blocks that make up a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="graph.cfg.edges",
        backend_method="cfg_edges",
        description="List control-flow edges between the basic blocks of a function.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="graph.call_paths",
        backend_method="callgraph_paths",
        description="Find call graph paths between two functions up to a chosen depth.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "source_function": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "target_function": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "max_depth": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "source_function", "target_function"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.analyzers.list",
        backend_method="analysis_analyzers_list",
        description=(
            "List boolean analyzers available for the current program and show"
            "whether each one is enabled."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "query": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.analyzers.set",
        backend_method="analysis_analyzers_set",
        description="Enable or disable a specific boolean analyzer for the current program.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "enabled": {"type": "boolean"},
            },
            "required": ["session_id", "name", "enabled"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="analysis.clear_cache",
        backend_method="analysis_clear_cache",
        description=(
            "Clear cached decompiler state for the current session so later requests"
            "rebuild it cleanly."
        ),
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.tokens",
        backend_method="decomp_tokens",
        description="Decompile a function and return tokenized Clang markup for the output.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.ast",
        backend_method="decomp_ast",
        description="Decompile a function and return the Clang markup tree for the result.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="pcode.block",
        backend_method="pcode_block",
        description="Return per-instruction p-code for the basic block containing an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="pcode.varnode_uses",
        backend_method="pcode_varnode_uses",
        description="Find p-code reads and writes that match a selected varnode.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "varnode": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "space": {"type": "string"},
                "size": {"type": "integer"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="task.analysis_update",
        backend_method="task_analysis_update",
        description="Start auto-analysis as a tracked background task and return a task ID.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="task.status",
        backend_method="task_status",
        description=("Return status, timing, and cancellation details for an asynchronoustask."),
        input_schema={
            "type": "object",
            "properties": {"task_id": {"type": "string"}},
            "required": ["task_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="task.result",
        backend_method="task_result",
        description="Return the terminal result or error payload for a completed task.",
        input_schema={
            "type": "object",
            "properties": {"task_id": {"type": "string"}},
            "required": ["task_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="task.cancel",
        backend_method="task_cancel",
        description="Request cancellation for a running or queued asynchronous task.",
        input_schema={
            "type": "object",
            "properties": {"task_id": {"type": "string"}},
            "required": ["task_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="decomp.high_function.summary",
        backend_method="decomp_high_function_summary",
        description=(
            "Summarize the high-function view, including local symbols, globals,"
            "blocks, and jump tables."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.writeback.params",
        backend_method="decomp_writeback_params",
        description=(
            "Commit decompiler-recovered parameter information back into the programdatabase."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "use_data_types": {"type": "boolean"},
                "commit_return": {"type": "boolean"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.writeback.locals",
        backend_method="decomp_writeback_locals",
        description="Commit decompiler-recovered local names back into the program database.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.override.get",
        backend_method="decomp_override_get",
        description="Return the decompiler call override, if any, for a specific callsite.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "callsite": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "function_start", "callsite"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.override.set",
        backend_method="decomp_override_set",
        description=(
            "Set or replace the decompiler call override signature for a specificcallsite."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "callsite": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "signature": {"type": "string"},
            },
            "required": ["session_id", "function_start", "callsite", "signature"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.trace_type.forward",
        backend_method="decomp_trace_type_forward",
        description="Trace type propagation forward from a selected decompiler symbol.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "ordinal": {"type": "integer"},
                "storage": {"type": "string"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.trace_type.backward",
        backend_method="decomp_trace_type_backward",
        description="Trace type propagation backward from a selected decompiler symbol.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "ordinal": {"type": "integer"},
                "storage": {"type": "string"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "name"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.global.rename",
        backend_method="decomp_global_rename",
        description=("Rename a global symbol selected through decompiler high-symbolinformation."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "new_name": {"type": "string"},
                "storage": {"type": "string"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "name", "new_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="decomp.global.retype",
        backend_method="decomp_global_retype",
        description=("Retype a global symbol selected through decompiler high-symbolinformation."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "function_start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "data_type": {"type": "string"},
                "storage": {"type": "string"},
                "timeout_secs": {"type": "integer"},
            },
            "required": ["session_id", "function_start", "name", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
)
