"""Memory, listing, context, and patch tool specs."""

from __future__ import annotations

from .schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="memory.blocks.list",
        backend_method="binary_memory_blocks",
        description="List memory blocks together with addresses, permissions, and sizes.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.data.list",
        backend_method="binary_data",
        description=("List defined data items in the program with range and paginationcontrols."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.disassemble.function",
        backend_method="disasm_function",
        description="Disassemble all instructions that belong to a function body.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.disassemble.range",
        backend_method="disasm_range",
        description="Disassemble instructions across a selected address range.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id", "start", "length"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="memory.read",
        backend_method="memory_read",
        description="Read raw bytes directly from program memory.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "address", "length"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="memory.write",
        backend_method="memory_write",
        description="Write raw bytes directly into program memory.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_base64": {"type": "string"},
                "data_hex": {"type": "string"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.data.at",
        backend_method="data_typed_at",
        description="Return the defined data item at a specific address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.data.create",
        backend_method="data_create",
        description="Create a data definition of a chosen type at an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "data_type": {"type": "string"},
                "length": {"type": "integer"},
                "clear_existing": {"type": "boolean"},
            },
            "required": ["session_id", "address", "data_type"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.data.clear",
        backend_method="data_clear",
        description="Clear one or more data definitions starting at an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="patch.assemble",
        backend_method="patch_assemble",
        description="Assemble instruction text at an address and write the resulting bytes.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "assembly": {"type": "string"},
            },
            "required": ["session_id", "address", "assembly"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="patch.nop",
        backend_method="patch_nop",
        description="Replace instructions in a range with NOP bytes.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "count": {"type": "integer"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="patch.branch_invert",
        backend_method="patch_branch_invert",
        description="Invert a conditional branch instruction in place.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="memory.block.create",
        backend_method="memory_block_create",
        description=(
            "Create a memory block with permissions, initialization, and an optionalcomment."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
                "initialized": {"type": "boolean"},
                "fill": {"type": "integer"},
                "read": {"type": "boolean"},
                "write": {"type": "boolean"},
                "execute": {"type": "boolean"},
                "comment": {"type": "string"},
            },
            "required": ["session_id", "name", "address", "length"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="memory.block.remove",
        backend_method="memory_block_remove",
        description="Remove an existing memory block from the program.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.code_units.list",
        backend_method="listing_code_units_list",
        description="List code units in a range with pagination and direction controls.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "forward": {"type": "boolean"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.code_unit.at",
        backend_method="listing_code_unit_at",
        description="Return the code unit that starts exactly at a given address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.code_unit.before",
        backend_method="listing_code_unit_before",
        description="Return the nearest code unit that precedes a given address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.code_unit.after",
        backend_method="listing_code_unit_after",
        description="Return the nearest code unit that follows a given address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.code_unit.containing",
        backend_method="listing_code_unit_containing",
        description="Return the code unit that contains a given address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.clear",
        backend_method="listing_clear",
        description=(
            "Clear listing content over a range, including optional symbols,"
            "comments, references, functions, or context."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
                "clear_context": {"type": "boolean"},
                "clear_symbols": {"type": "boolean"},
                "clear_comments": {"type": "boolean"},
                "clear_properties": {"type": "boolean"},
                "clear_functions": {"type": "boolean"},
                "clear_registers": {"type": "boolean"},
                "clear_equates": {"type": "boolean"},
                "clear_user_references": {"type": "boolean"},
                "clear_analysis_references": {"type": "boolean"},
                "clear_import_references": {"type": "boolean"},
                "clear_default_references": {"type": "boolean"},
                "clear_bookmarks": {"type": "boolean"},
            },
            "required": ["session_id", "start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="listing.disassemble.seed",
        backend_method="listing_disassemble_seed",
        description="Start disassembly from a seed address and follow discovered flows.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
                "clear_existing": {"type": "boolean"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="context.get",
        backend_method="context_get",
        description="Return processor context register values at a specific address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "register": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "signed": {"type": "boolean"},
            },
            "required": ["session_id", "register", "address"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="context.set",
        backend_method="context_set",
        description="Set processor context register values across an address range.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "register": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
                "value": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "clear": {"type": "boolean"},
            },
            "required": ["session_id", "register", "start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="context.ranges",
        backend_method="context_ranges",
        description="List address ranges where a processor context register value applies.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "register": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "register"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
)
