"""Program, project, transaction, ghidra, and metadata tool specs."""

from __future__ import annotations

from .schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="ghidra.info",
        backend_method="ghidra_info",
        description=(
            "Return runtime information about Ghidra, PyGhidra, and the serverenvironment."
        ),
        input_schema={
            "type": "object",
            "properties": {},
            "required": [],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.open",
        backend_method="session_open",
        description="Open a binary file for analysis and return a new session.",
        input_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "update_analysis": {"type": "boolean"},
                "read_only": {"type": "boolean"},
                "project_location": {"type": "string"},
                "project_name": {"type": "string"},
                "program_name": {"type": "string"},
                "language": {"type": "string"},
                "compiler": {"type": "string"},
                "loader": {"type": "string"},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.open_bytes",
        backend_method="session_open_bytes",
        description="Open a binary from base64-encoded bytes and return a new session.",
        input_schema={
            "type": "object",
            "properties": {
                "data_base64": {"type": "string"},
                "filename": {"type": "string"},
                "update_analysis": {"type": "boolean"},
                "read_only": {"type": "boolean"},
                "project_location": {"type": "string"},
                "project_name": {"type": "string"},
                "program_name": {"type": "string"},
                "language": {"type": "string"},
                "compiler": {"type": "string"},
                "loader": {"type": "string"},
            },
            "required": ["data_base64"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="project.program.open_existing",
        backend_method="session_open_existing",
        description=(
            "Open a program from a named existing Ghidra project and return a newsession."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "project_location": {"type": "string"},
                "project_name": {"type": "string"},
                "program_path": {"type": "string"},
                "folder_path": {"type": "string"},
                "program_name": {"type": "string"},
                "read_only": {"type": "boolean"},
                "update_analysis": {"type": "boolean"},
            },
            "required": ["project_location", "project_name"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.close",
        backend_method="session_close",
        description="Close an open program session and release its associated resources.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.list_open",
        backend_method="session_list",
        description="List all program sessions currently held open by the server.",
        input_schema={
            "type": "object",
            "properties": {},
            "required": [],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.mode.get",
        backend_method="session_mode",
        description="Return whether a session is currently read-only or read-write.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="program.mode.set",
        backend_method="session_set_mode",
        description="Switch a session between read-only and read-write mode.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "read_only": {"type": "boolean"},
                "deterministic": {"type": "boolean"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="program.summary",
        backend_method="binary_summary",
        description=(
            "Return core program metadata such as architecture, memory layout, andentry point."
        ),
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="program.save",
        backend_method="session_save",
        description="Save the current program state back into the project.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.save_as",
        backend_method="session_save_as",
        description="Save the current program under a new project path or name.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "program_name": {"type": "string"},
                "folder_path": {"type": "string"},
                "overwrite": {"type": "boolean"},
            },
            "required": ["session_id", "program_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="project.export",
        backend_method="session_export_project",
        description="Export the current Ghidra project artifacts to a destination directory.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "destination": {"type": "string"}},
            "required": ["session_id", "destination"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="program.export_binary",
        backend_method="session_export_binary",
        description=("Export the program to disk as either the original-file format or rawbytes."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "format": {"type": "string"},
            },
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="metadata.store",
        backend_method="metadata_store",
        description="Store a JSON-serializable metadata value under a program-scoped key.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "key": {"type": "string"},
                "value": {},
            },
            "required": ["session_id", "key", "value"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="metadata.query",
        backend_method="metadata_query",
        description=(
            "Read metadata entries stored by this server, optionally filtered by keyor prefix."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "key": {"type": "string"},
                "prefix": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="program.report",
        backend_method="report_program_summary",
        description=(
            "Return a compact program report with counts plus sample functions,"
            "strings, imports, and memory blocks."
        ),
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="program.image_base.set",
        backend_method="binary_rebase",
        description=(
            "Change the program image base. The rebase is always applied to the open"
            "program in memory; commit controls whether the change is recorded in the"
            "undo stack."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "image_base": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "commit": {"type": "boolean"},
            },
            "required": ["session_id", "image_base"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="transaction.begin",
        backend_method="undo_begin",
        description="Begin an explicit undo transaction for grouped changes.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "description": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="transaction.commit",
        backend_method="undo_commit",
        description="Commit the active transaction so its changes become undoable.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="transaction.revert",
        backend_method="undo_revert",
        description="Roll back the active transaction without committing it.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="transaction.undo",
        backend_method="undo_undo",
        description="Undo the most recently committed change.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="transaction.redo",
        backend_method="undo_redo",
        description="Reapply the most recently undone change.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="transaction.status",
        backend_method="undo_status",
        description="Return undo, redo, and active-transaction status for the session.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="ghidra.call",
        backend_method="call_api",
        description=(
            "Invoke Ghidra or Java APIs directly through a generic bridge. Raw access"
            "to a read-only session requires write=true and transitions it to"
            "writable."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "target": {"type": "string"},
                "args": {"type": "array", "items": {}},
                "kwargs": {"type": "object"},
                "session_id": {"type": "string"},
                "write": {"type": "boolean"},
            },
            "required": ["target"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=True,
        batch_allowed=False,
    ),
    ToolSpec(
        name="ghidra.eval",
        backend_method="eval_code",
        description=(
            "Evaluate Python code inside the live Ghidra runtime context. Raw access"
            "to a read-only session requires write=true and transitions it to"
            "writable."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "code": {"type": "string"},
                "session_id": {"type": "string"},
                "write": {"type": "boolean"},
            },
            "required": ["code"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=True,
        batch_allowed=False,
    ),
    ToolSpec(
        name="ghidra.script",
        backend_method="run_script",
        description=(
            "Run a Ghidra script against an open program session. Raw access to a"
            "read-only session requires write=true and transitions it to writable."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "session_id": {"type": "string"},
                "script_args": {"type": "array", "items": {"type": "string"}},
                "write": {"type": "boolean"},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=True,
        batch_allowed=False,
    ),
    ToolSpec(
        name="project.folders.list",
        backend_method="project_folders_list",
        description="List project folders, optionally walking the tree recursively.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "folder_path": {"type": "string"},
                "recursive": {"type": "boolean"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="project.files.list",
        backend_method="project_files_list",
        description=("List project files with folder, content-type, query, and paginationfilters."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "folder_path": {"type": "string"},
                "recursive": {"type": "boolean"},
                "content_type": {"type": "string"},
                "query": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="project.file.info",
        backend_method="project_file_info",
        description="Return metadata and state flags for a specific project file.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "path": {"type": "string"}},
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="project.program.open",
        backend_method="project_program_open",
        description=(
            "Open a program already stored in the current project and return a newsession."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "read_only": {"type": "boolean"},
                "update_analysis": {"type": "boolean"},
            },
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="project.search.programs",
        backend_method="project_search_programs",
        description="Search program files in the project by name or path.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "query": {"type": "string"},
                "content_type": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="program.export_packed",
        backend_method="program_export_packed",
        description="Export the program to disk as a lossless Ghidra packed file (GZF).",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "destination_path": {"type": "string"},
                "overwrite": {"type": "boolean"},
            },
            "required": ["session_id", "destination_path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=False,
        open_world=False,
        batch_allowed=False,
    ),
    ToolSpec(
        name="project.file.delete",
        backend_method="project_file_delete",
        description=("Delete a project file by exact project path; rejects an open domainobject."),
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "path": {"type": "string"}},
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=False,
    ),
)
