"""External, reference, equate, source, and relocation tool specs."""

from __future__ import annotations

from .schema import ToolSpec

TOOL_SPECS: tuple[ToolSpec, ...] = (
    ToolSpec(
        name="external.imports.list",
        backend_method="binary_imports",
        description="List symbols imported by the program.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.exports.list",
        backend_method="binary_exports",
        description="List symbols exported by the program.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.to",
        backend_method="xref_to",
        description="List cross-references that target an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.from",
        backend_method="xref_from",
        description="List cross-references that originate from an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.library.list",
        backend_method="external_library_list",
        description="List external libraries known to the program.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.location.get",
        backend_method="external_location_get",
        description="Return details for a specific external location.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.library.create",
        backend_method="external_library_create",
        description="Create a new external library record.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "name": {"type": "string"}},
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.library.set_path",
        backend_method="external_library_set_path",
        description="Set or update the filesystem path associated with an external library.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "path": {"type": "string"},
                "user_defined": {"type": "boolean"},
            },
            "required": ["session_id", "name", "path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.location.create",
        backend_method="external_location_create",
        description="Create an external location for a symbol within a library.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "library_name": {"type": "string"},
                "label": {"type": "string"},
                "external_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "library_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.function.create",
        backend_method="external_function_create",
        description="Create an external function symbol under an external location.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "library_name": {"type": "string"},
                "name": {"type": "string"},
                "external_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "library_name", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.entrypoint.add",
        backend_method="external_entrypoint_add",
        description="Add an address to the program's external entry point set.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.entrypoint.remove",
        backend_method="external_entrypoint_remove",
        description="Remove an address from the external entry point set.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="external.entrypoint.list",
        backend_method="external_entrypoint_list",
        description="List addresses currently marked as external entry points.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.create.memory",
        backend_method="reference_create_memory",
        description="Create a memory reference between two program addresses.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "to_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "reference_type": {"type": "string"},
                "operand_index": {"type": "integer"},
                "source_type": {"type": "string"},
            },
            "required": ["session_id", "from_address", "to_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.create.stack",
        backend_method="reference_create_stack",
        description="Create a reference from an address to a stack location.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "stack_offset": {"type": "integer"},
                "reference_type": {"type": "string"},
                "operand_index": {"type": "integer"},
                "source_type": {"type": "string"},
            },
            "required": ["session_id", "from_address", "stack_offset"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.create.register",
        backend_method="reference_create_register",
        description="Create a reference from an address to a register.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "register": {"type": "string"},
                "reference_type": {"type": "string"},
                "operand_index": {"type": "integer"},
                "source_type": {"type": "string"},
            },
            "required": ["session_id", "from_address", "register"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.create.external",
        backend_method="reference_create_external",
        description="Create a reference from an address to an external location.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "library_name": {"type": "string"},
                "label": {"type": "string"},
                "external_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "reference_type": {"type": "string"},
                "operand_index": {"type": "integer"},
                "source_type": {"type": "string"},
            },
            "required": ["session_id", "from_address", "library_name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.delete",
        backend_method="reference_delete",
        description=("Delete a specific reference selected by source, destination, andoperand."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "to_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
            },
            "required": ["session_id", "from_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.clear_from",
        backend_method="reference_clear_from",
        description="Remove references originating from one address or an address range.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "from_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.clear_to",
        backend_method="reference_clear_to",
        description="Remove all references that target a specific address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "to_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "to_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.primary.set",
        backend_method="reference_primary_set",
        description="Mark a specific reference as the primary one for its operand.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "to_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
            },
            "required": ["session_id", "from_address", "to_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.association.set",
        backend_method="reference_association_set",
        description="Associate a specific reference with a symbol.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "to_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
                "symbol_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "symbol_name": {"type": "string"},
            },
            "required": ["session_id", "from_address", "to_address", "symbol_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="reference.association.remove",
        backend_method="reference_association_remove",
        description="Remove the symbol association attached to a specific reference.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "from_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "to_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
            },
            "required": ["session_id", "from_address", "to_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="equate.create",
        backend_method="equate_create",
        description="Create an equate and attach it to an operand at an address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "name": {"type": "string"},
                "value": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
            },
            "required": ["session_id", "address", "name", "value"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="equate.list",
        backend_method="equate_list",
        description="List equates together with values and attached references.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="equate.delete",
        backend_method="equate_delete",
        description=("Delete an equate entirely, or remove one of its references beforedeletion."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "name": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "operand_index": {"type": "integer"},
            },
            "required": ["session_id", "name"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="equate.clear_range",
        backend_method="equate_clear_range",
        description=("Remove equate references across an address range and delete emptyequates."),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "start"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="source.file.list",
        backend_method="source_file_list",
        description="List all source files currently registered with the program.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}},
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="source.file.add",
        backend_method="source_file_add",
        description="Register a source file record with the program's source file manager.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "id_type": {"type": "string"},
                "identifier_hex": {"type": "string"},
            },
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="source.file.remove",
        backend_method="source_file_remove",
        description="Remove a source file record by path.",
        input_schema={
            "type": "object",
            "properties": {"session_id": {"type": "string"}, "path": {"type": "string"}},
            "required": ["session_id", "path"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="source.map.list",
        backend_method="source_map_list",
        description="List source mapping entries by address, source file, or line filters.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "path": {"type": "string"},
                "min_line": {"type": "integer"},
                "max_line": {"type": "integer"},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="source.map.add",
        backend_method="source_map_add",
        description="Add a source mapping entry from a source line to an address range.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "line_number": {"type": "integer"},
                "base_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "length": {"type": "integer"},
            },
            "required": ["session_id", "path", "line_number", "base_address", "length"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="source.map.remove",
        backend_method="source_map_remove",
        description="Remove a specific source mapping entry by file, line, and base address.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "path": {"type": "string"},
                "line_number": {"type": "integer"},
                "base_address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id", "path", "line_number", "base_address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="relocation.list",
        backend_method="relocation_list",
        description="List relocation entries, optionally limited to an address range.",
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "start": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "end": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
            },
            "required": ["session_id"],
            "additionalProperties": False,
        },
        read_only=True,
        destructive=False,
        open_world=False,
        batch_allowed=True,
    ),
    ToolSpec(
        name="relocation.add",
        backend_method="relocation_add",
        description=(
            "Add a relocation entry at an address with type, status, values, andsymbol metadata."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "session_id": {"type": "string"},
                "address": {"oneOf": [{"type": "integer"}, {"type": "string"}]},
                "status": {"type": "string"},
                "type": {"type": "integer"},
                "values": {"type": "array", "items": {"type": "integer"}},
                "byte_length": {"type": "integer"},
                "symbol_name": {"type": "string"},
            },
            "required": ["session_id", "address"],
            "additionalProperties": False,
        },
        read_only=False,
        destructive=True,
        open_world=False,
        batch_allowed=True,
    ),
)
